[project]
name = "ldoce5viewer-pyqt5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "lxml==4.9.2",
    "pyqt5==5.15.2",
    "pyqt5-sip==12.12.1",
    "pyqtwebkit==5.15.2",
    "whoosh==2.7.4",
]
